//
//
//	Name:			Mark Barros
//	Course:			CS1400 - Intro to Programming and Problem Solving
//	Description:	This project allows the user to try and guess a number between one and
//					one-hundred that is randomly generated by the program.
//
//

import java.util.Random;
import java.util.Scanner;

public class GuessingGame
{
    public static void main(String[] args)
    {
        Scanner keyboard = new Scanner(System.in);
        Random randomNumberGenerator = new Random();
        int secretNumber = randomNumberGenerator.nextInt(100) + 1;
        int guessCount = 1;

        System.out.print("Mark's Number Guessing Game\n\n");
        System.out.print("A secret number between 1-100 has been generated...\n\n");
        System.out.print("Enter your guess? ");

        // needed in the event that the user quits before even starting:
        int guess = keyboard.nextInt();

        while (guessCount <= 7 && guess !=  0 && guess != secretNumber) {

            if (guess > secretNumber) {
                System.out.print("Guess is high, try again.\nEnter your guess? ");
            }
            else if (guess < secretNumber) {
                System.out.print("Guess is low, try again.\nEnter your guess? ");
            }
            guess = keyboard.nextInt();
            guessCount++;
        }
        keyboard.close();

        if (guess == secretNumber) {
            System.out.println("Correct in " + guessCount + " guesses.");
        }
        else {
            System.out.println("The secret number is " + secretNumber + ".");
        }
    }
}
